name: Build & push Docker images

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME_AGENT: prometheus-agent
  IMAGE_NAME_SERVER: prometheus-target-server

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ gitea.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3

      - name: Login to private registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image (agent)
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/agent.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_HOST }}/${{ env.IMAGE_NAME_AGENT }}:${{ gitea.sha }}
            ${{ secrets.DOCKER_REGISTRY_HOST }}/${{ env.IMAGE_NAME_AGENT }}:main

      - name: Build and push Docker image (server)
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/server.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_HOST }}/${{ env.IMAGE_NAME_SERVER }}:${{ gitea.sha }}
            ${{ secrets.DOCKER_REGISTRY_HOST }}/${{ env.IMAGE_NAME_SERVER }}:main
